### ISSUE TITLE
Error copying to stream

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#46] opened 2023-06-08 11:39 UTC
When making a job the first time, there was an error code in machine.job:

```
[41m[30mfail[39m[22m[49m: Hangfire.AutomaticRetryAttribute[0]
      Failed to process the job '64814c54761d983ab9eaeeb2': an exception occurred.
      System.Net.Http.HttpRequestException: Error while copying content to a stream.
       ---> System.IO.IOException: Unable to write data to the transport connection: Broken pipe.
       ---> System.Net.Sockets.SocketException (32): Broken pipe
         --- End of inner exception stack trace ---
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Security.SslStream.<WriteSingleChunk>g__CompleteWriteAsync|182_1[TIOAdapter](ValueTask writeTask, Byte[] bufferToReturn)
         at System.Net.Security.SslStream.WriteAsyncChunked[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
         at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
         at System.Net.Http.HttpConnection.WriteAsync(ReadOnlyMemory`1 source, Boolean async)
         at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
         at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at SIL.Machine.AspNetCore.Services.S3AuthHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/S3AuthHandler.cs:line 36
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at SIL.Machine.AspNetCore.Services.S3FileStorage.UploadPartAsync(String key, String uploadId, Int32 partNumber, Byte[] buffer, Int32 count) in /app/src/SIL.Machine.AspNetCore/Services/S3FileStorage.cs:line 206
         at SIL.Machine.AspNetCore.Services.S3WriteStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs:line 53
         at System.IO.BufferedStream.WriteToUnderlyingStreamAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken, Task semaphoreLockTask)
         at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
         at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
         at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
         at SIL.Machine.AspNetCore.Services.ClearMLNmtEngineBuildJob.WriteDataFilesAsync(String buildId, IReadOnlyList`1 corpora, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs:line 293
         at SIL.Machine.AspNetCore.Services.ClearMLNmtEngineBuildJob.WriteDataFilesAsync(String buildId, IReadOnlyList`1 corpora, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs:line 299
         at SIL.Machine.AspNetCore.Services.ClearMLNmtEngineBuildJob.WriteDataFilesAsync(String buildId, IReadOnlyList`1 corpora, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs:line 299
         at SIL.Machine.AspNetCore.Services.ClearMLNmtEngineBuildJob.WriteDataFilesAsync(String buildId, IReadOnlyList`1 corpora, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs:line 299
         at SIL.Machine.AspNetCore.Services.ClearMLNmtEngineBuildJob.RunAsync(String engineId, String buildId, IReadOnlyList`1 corpora, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs:line 58
         at SIL.Machine.AspNetCore.Services.ClearMLNmtEngineBuildJob.RunAsync(String engineId, String buildId, IReadOnlyList`1 corpora, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs:line 234
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Let's fix this.

**Comment by ddaspit** [comment] 2023-06-13 11:02
If this is caused by an unstable connection to S3, then we should retry the request multiple times. We can use [Polly](https://github.com/App-vNext/Polly) to enable this kind of functionality. [Here](https://github.com/sillsdev/serval/blob/981cf06589ebd035f3b4000d32bdafbe16fc38de/src/Serval.Webhooks/Configuration/IServalBuilderExtensions.cs#L9) is an example of configuring Polly for an `HttpClient` instance.

**Comment by Enkidu93** [comment] 2023-07-20 15:32
Is this repeatable, @johnml1135 ?

**Comment by Enkidu93** [comment] 2023-07-21 18:18
Would you be opposed to creating separate local file and s3 classes that inherit from `SharedFileService`? This would keep it extensible, but it should allow me to inject a correctly configured httpClient. The issue I'm having now is that `S3FileStorage` has its own `DelegateHandler` (i.e. `S3AuthHandler`) which I need to incorporate and configure properly while still setting up Polly at the MachineBuilder level.

If this doesn't seem tenable, let me know. I want to find a solution that's relatively clean and keeps things modular. Alternatively, I could add retry logic to the S3AuthHandler itself, but it wouldn't be using Polly. Another option would be switching to using the AWS SDK itself like John mentioned. If I'm missing something entirely, let me know.

**Comment by johnml1135** [comment] 2023-07-21 19:41
@Enkidu93 - can you show me what you are thinking for using Polly?  I have a hard time imagining it...

**Comment by johnml1135** [comment] 2023-07-23 11:14
Let’s connect about this on Monday.  If you could walk me through the code,
and the options that would be great.

**Comment by johnml1135** [comment] 2023-07-26 14:31
Our understanding is that we are using S3 buckets in a very standard way.  We also anticipate using them more to move data around for other SMT or NMT jobs or realtime inferencing.  Therefore, let's just use the standard solution that is supported by aws -  https://www.nuget.org/packages/AWSSDK.S3

**Comment by Enkidu93** [comment] 2023-08-03 17:53
@ddaspit  Do you have any reservations about this (i.e. moving to using the Amazon S3 SDK)? It will involve a good bit of reworking, so I wanted to check before I went further.

**Comment by ddaspit** [comment] 2023-08-03 18:03
I was trying to use the Stowage library, so that we could easily support other cloud storage services. It also provided a much simpler interface than the AWSSDK.S3 library. Unfortunately, I ran into issues with the S3 implementation in Stowage and had to copy the code and fix it. I always intended to submit the fixes back to the Stowage repo, but never got the chance. If Stowage is not working for us, then we can go ahead and use the AWSSDK.S3 library. The `ISharedFileService` interface should provide sufficient abstraction. We probably want to have a memory implementation as well for testing purposes.

**Comment by Enkidu93** [comment] 2023-08-04 19:01
OK, sounds good. I'm on it.

**Comment by Enkidu93** [comment] 2023-08-08 18:09
@johnml1135 See commit message above; thoughts? (It passed the E2E tests locally btw).

**Closed** 2023-08-22 14:15 UTC
Labels: bug
