### ISSUE TITLE
Call python from dotnet jobs for GPU python development without ClearML, all locally

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#105] opened 2023-10-05 17:31 UTC
A follow up to the python work began in https://github.com/sillsdev/machine/pull/101 - but left incomplete.  If we really want to use it, it needs to be fully integrated with machine.py and work in the different docker environments, especially dev.

**Comment by johnml1135** [comment] 2023-10-05 17:32
This primarily allows the full stack to be run completely locally on a computer with a GPU without needing ClearML in one docker image.  Great for debugging! but will need some work to get seamless.

**Comment by ddaspit** [comment] 2023-10-05 18:57
This is a duplicate of #103.

**Closed by ddaspit** 2023-10-05 18:57 UTC
Labels: enhancement
